uni_pe/accounts/urls.py
from django.urls import path

from . settings import EDITABLE_FIELDS
from . views import *


app_name = "accounts"

if EDITABLE_FIELDS:
    urlpatterns = [
        path('account/', account, name='account'),
        path('account/edit/', changeData, name='change_data'),
        path('account/edit/confirm-email/', confirmEmail, name='confirm_email'),
    ]
else:
    urlpatterns = []

uni_pe/pe_management/urls.py
from django.urls import path

from . api.views import (generic as api_generic,
                         user as api_user,
                         operator as api_evaluation_operator,
                         patronage as api_patronage_operator,
                         manager as api_manager,
                         involved_personnel as api_involved_personnel,
                         involved_structures as api_involved_structures)

from . views import (generic,
                     involved_personnel,
                     involved_structures,
                     manager,
                     operator,
                     patronage,
                     user)


app_name = 'pe_management'


# app prefix
prefix = 'pe-management'

api_prefix = "api"
user_prefix = 'user'
involved_personnel_prefix = 'involved-personnel'
involved_structures_prefix = 'involved-structures'
operator_prefix = 'operator'
validator_prefix = 'evaluation'
patronage_prefix = 'patronage'
manager_prefix = 'manager'

urlpatterns = [
    path(f'{prefix}/', generic.dashboard, name='dashboard'),
    path(f'{prefix}/events/<int:event_id>/poster/download/',
         generic.download_event_poster, name='download_event_poster'),

    # user
    path(f'{prefix}/{user_prefix}/events/', user.events, name='user_events'),
    path(f'{prefix}/{user_prefix}/events/new/',
         user.new_event_choose_referent, name='user_new_event_choose_referent'),
    path(f'{prefix}/{user_prefix}/events/new/basic-info/',
         user.new_event_basic_info, name='user_new_event_basic_info'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/',
         user.event, name='user_event'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/basic-info/',
         user.event_basic_info, name='user_event_basic_info'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/data/',
         user.event_data, name='user_event_data'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/report/',
         user.event_report, name='user_event_report'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/people/',
         user.event_people, name='user_event_people'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/people/delete/<int:person_id>/',
         user.event_people_delete, name='user_event_people_delete'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/structures/',
         user.event_structures, name='user_event_structures'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/structures/delete/<int:structure_id>/',
         user.event_structures_delete, name='user_event_structures_delete'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/request-evaluation/',
         user.event_request_evaluation, name='user_event_request_evaluation'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/request-evaluation-cancel/',
         user.event_request_evaluation_cancel, name='user_event_request_evaluation_cancel'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/clone/',
         user.event_clone, name='user_event_clone'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/delete/',
         user.event_delete, name='user_event_delete'),

    # evaluation operator
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/',
         operator.dashboard, name='operator_dashboard'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/',
         operator.events, name='operator_events'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/export/',
         operator.export, name='operator_export'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/',
         operator.event, name='operator_event'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/take/',
         operator.take_event, name='operator_take_event'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/basic-info/',
         operator.event_basic_info, name='operator_event_basic_info'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/data/',
         operator.event_data, name='operator_event_data'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/people/',
         operator.event_people, name='operator_event_people'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/people/delete/<int:person_id>/',
         operator.event_people_delete, name='operator_event_people_delete'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/structures/',
         operator.event_structures, name='operator_event_structures'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/structures/delete/<int:structure_id>/',
         operator.event_structures_delete, name='operator_event_structures_delete'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/evaluate/',
         operator.event_evaluation, name='operator_event_evaluation'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/reopen-evaluation/',
         operator.event_reopen_evaluation, name='operator_event_reopen_evaluation'),

    # patronage operator
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/',
         patronage.dashboard, name='patronage_operator_dashboard'),
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/<str:structure_slug>/events/',
         patronage.events, name='patronage_operator_events'),
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/<str:structure_slug>/events/<int:event_id>/',
         patronage.event, name='patronage_operator_event'),
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/<str:structure_slug>/events/<int:event_id>/take/',
         patronage.take_event, name='patronage_operator_take_event'),
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/<str:structure_slug>/events/<int:event_id>/evaluate/',
         patronage.event_evaluation, name='patronage_operator_event_evaluation'),
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/<str:structure_slug>/events/<int:event_id>/reopen-evaluation/',
         patronage.event_reopen_evaluation, name='patronage_operator_event_reopen_evaluation'),

    # involved structures
    path(f'{prefix}/{operator_prefix}/{involved_structures_prefix}/',
         involved_structures.dashboard, name='involved_structures_dashboard'),
    path(f'{prefix}/{operator_prefix}/{involved_structures_prefix}/<str:structure_slug>/events/',
         involved_structures.events, name='involved_structures_events'),
    path(f'{prefix}/{operator_prefix}/{involved_structures_prefix}/<str:structure_slug>/events/<int:event_id>/',
         involved_structures.event, name='involved_structures_event'),

    # manager
    path(f'{prefix}/{manager_prefix}/',
         manager.dashboard, name='manager_dashboard'),
    path(f'{prefix}/{manager_prefix}/export/',
         manager.export, name='manager_export'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/',
         manager.events, name='manager_events'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/new/',
         manager.new_event_choose_referent, name='manager_new_event_choose_referent'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/new/basic-info/',
         manager.new_event_basic_info, name='manager_new_event_basic_info'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/',
         manager.event, name='manager_event'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/basic-info/',
         manager.event_basic_info, name='manager_event_basic_info'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/data/',
         manager.event_data, name='manager_event_data'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/people/',
         manager.event_people, name='manager_event_people'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/people/delete/<int:person_id>/',
         manager.event_people_delete, name='manager_event_people_delete'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/structures/',
         manager.event_structures, name='manager_event_structures'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/structures/delete/<int:structure_id>/',
         manager.event_structures_delete, name='manager_event_structures_delete'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/report/',
         manager.event_report, name='manager_event_report'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/change-status/',
         manager.event_enable_disable, name='manager_event_enable_disable'),

    # involved personnel
    path(f'{prefix}/{involved_personnel_prefix}/events/',
         involved_personnel.events, name='involved_personnel_events'),
    path(f'{prefix}/{involved_personnel_prefix}/events/<int:event_id>/',
         involved_personnel.event, name='involved_personnel_event'),

    # API
    path(f'{prefix}/{api_prefix}/structures/',
         api_generic.OrganizationalStructureList.as_view(), name='api_structures'),
    path(f'{prefix}/{api_prefix}/events/',
         api_generic.PublicEngagementApprovedEventList.as_view(), name='api_generic_approved_events'),
    path(f'{prefix}/{api_prefix}/events/<int:pk>/',
         api_generic.PublicEngagementApprovedEventDetail.as_view(), name='api_generic_approved_event'),
    path(f'{prefix}/{api_prefix}/{user_prefix}/events/',

uni_pe/template/urls.py
from django.urls import path
from pe_management.views import generic

app_name = 'template'

urlpatterns = [
    path('', generic.dashboard, name='dashboard'),
]

uni_pe/uni_pe/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

# from rest_framework.documentation import include_docs_urls
# from rest_framework.schemas import get_schema_view


urlpatterns = [
    path(f'{settings.ADMIN_PATH}/', admin.site.urls),
    # path('docs/', include_docs_urls(title=API_TITLE, description=API_DESCRIPTION)),
    # path('schema/', get_schema_view(title=API_TITLE)),
]

urlpatterns += path('', include('pe_management.urls', namespace='public_engagement')),
urlpatterns += path('', include('template.urls', namespace='template')),
urlpatterns += path('', include('accounts.urls', namespace='accounts')),

if 'saml2_sp' in settings.INSTALLED_APPS:
    from djangosaml2 import views as saml2_views

    import saml2_sp.urls

    urlpatterns += path('', include((saml2_sp.urls, 'sp',))),

    urlpatterns += path('{}/login/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LoginView.as_view(), name='login'),
    urlpatterns += path('{}/acs/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.AssertionConsumerServiceView.as_view(), name='saml2_acs'),
    urlpatterns += path('{}/logout/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LogoutInitView.as_view(), name='logout'),
    urlpatterns += path('{}/ls/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LogoutView.as_view(), name='saml2_ls'),
    urlpatterns += path('{}/ls/post/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LogoutView.as_view(), name='saml2_ls_post'),
    urlpatterns += path('{}/metadata/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.MetadataView.as_view(), name='saml2_metadata'),
else:
    urlpatterns += path('{}/login/'.format(settings.LOCAL_URL_PREFIX),
                        auth_views.LoginView.as_view(
                            template_name='login.html'),
                        name='login'),
    urlpatterns += path('{}/logout/'.format(settings.LOCAL_URL_PREFIX),
                        auth_views.LogoutView.as_view(
                            template_name='logout.html', next_page='/'),
                        name='logout'),

uni_pe/pe_management/api/views/patronage.py
from django.db.models import Q
from django.utils import timezone
from rest_framework import permissions

from ...models import PublicEngagementAnnualMonitoring, PublicEngagementEvent
from ..permissions import IsStructurePatronageOperator
from .generic import PublicEngagementEventList


class PublicEngagementEventList(PublicEngagementEventList):
    permission_classes = [permissions.IsAuthenticated, IsStructurePatronageOperator]

    def get_queryset(self, **kwargs):
        """ """
        events = (
            PublicEngagementEvent.objects.prefetch_related("data", "report")
            .select_related("referent", "structure")
            .filter(
                structure__slug=self.kwargs["structure_slug"],
                structure__is_active=True,
                to_evaluate=True,
                data__patronage_requested=True,
            )
        )

        status = self.request.query_params.get("status")
        if status == "to_handle" or status == "to_evaluate":
            active_years = PublicEngagementAnnualMonitoring.objects.filter(
                is_active=True
            ).values_list("year", flat=True)
            years_query = Q()
            for year in active_years:
                years_query |= Q(start__year=year)

        if status == "to_handle":
            events = events.filter(
                years_query,
                data__patronage_requested=True,
                operator_evaluation_success=True,
                patronage_operator_taken_date__isnull=True,
                created_by_manager=False,
                start__gte=timezone.now(),
            )
        elif status == "to_evaluate":
            events = events.filter(
                years_query,
                data__patronage_requested=True,
                patronage_operator_taken_date__isnull=False,
                patronage_granted_date__isnull=True,
                created_by_manager=False,
                start__gte=timezone.now(),
            )
        elif status == "approved":
            events = events.filter(
                patronage_granted=True, patronage_granted_date__isnull=False
            )
        elif status == "rejected":
            events = events.filter(
                patronage_granted=False, patronage_granted_date__isnull=False
            )

        not_eligible = self.request.query_params.get("not_eligible")
        if not_eligible == "true":
            events = events.filter(is_active=False)

        return events

uni_pe/template/templates/patronage/dashboard.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}
{% load pe_management_tags %}


{% block top_content %}
<h2>{% trans "Structures" %}</h2>
<p>{% trans "Choose the structure to manage" %}</p>
<small>{% trans "The counters only take charge of the events for which the monitoring year is still active" %}.</small>
{% endblock top_content %}

{% block clean_content %}
<div class="row mt-5">
    {% for structure in structures %}
    <div class="col-12 col-lg-3">
        <!--start card-->
        <div class="card-wrapper card-space">
            <div class="card card-bg">
                <div class="card-body">
                    <h5 class="card-title">
                        {{ structure }}
                    </h5>
                    <hr>
                    <p>
                        <small>
                            <b>{% trans "Active monitoring" %}</b>
                            {% trans "To be handled" %}:
                            {% filter_events_per_structure_id event_counts structure.pk as structure_events %}
                            {% if structure_events.0.to_handle_count  %}
                            <span class="badge bg-info">{{ structure_events.0.to_handle_count }}</span>
                            {% else %}
                            0
                            {% endif %}
                            <br>
                            {% trans "To evaluate" %}:
                            {% if structure_events.0.to_evaluate_count %}
                            <span class="badge bg-warning">{{ structure_events.0.to_evaluate_count }}</span>
                            {% else %}
                            0
                            {% endif %}
                        </small>
                    </p>
                    <hr>
                    <a class="read-more" href="{% url 'pe_management:patronage_operator_events' structure_slug=structure.slug %}">
                        <span class="text text-primary">{% trans "Manage" %}</span>
                        <svg class="icon">
                            <use href="{% static 'svg/sprites.svg' %}#it-arrow-right-circle"></use>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
        <!--end card-->
    </div>
    {% endfor %}
</div>
{% endblock clean_content %}

uni_pe/template/templates/patronage/event.html
{% extends 'event.html' %}

{% load i18n %}
{% load static %}

{% load pe_management_tags %}


{% block actions %}
<div class="text-end mt-5">
{% if event.can_be_handled_for_patronage %}
<button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#take_event">
    <svg class="icon icon-sm icon-white">
        <use xlink:href="{% static 'svg/sprites.svg' %}#it-check"></use>
    </svg> {% trans "Handle" %}
</button>
<div class="it-example-modal d-inline">
   <div class="modal" tabindex="-1" role="dialog" id="take_event" aria-labelledby="take_event-Title">
      <div class="modal-dialog" role="document">
         <div class="modal-content">
            <div class="modal-header">
               <h2 class="modal-title h5" id="take_event-Title">{% trans "Confirm" %}</h2>
               <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Chiudi finestra modale">
                  <svg class="icon"><use href="{% static 'svg/sprites.svg' %}#it-close"></use></svg>
               </button>
            </div>
            <div class="modal-body">
               <p>{% trans "Do you want to proceed?" %}</p>
            </div>
            <div class="modal-footer">
                <form action="{% url 'pe_management:patronage_operator_take_event' structure_slug=structure_slug event_id=event.pk %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-success" type="submit">
                        {% trans 'Yes, proceed' %}
                    </button>
                </form>
            </div>
         </div>
      </div>
   </div>
</div>
{% endif %}

{% if event.is_ready_for_patronage_check %}
<a class="btn btn-success" href="{% url 'pe_management:patronage_operator_event_evaluation' structure_slug=structure_slug event_id=event.pk %}">
    <svg class="icon icon-sm icon-white">
        <use xlink:href="{% static 'svg/sprites.svg' %}#it-check"></use>
    </svg> {% trans "Evaluate" %} {% trans "patronage" %}
</a>
{% elif event.patronage_can_be_reviewed %}
<button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#reopen_evaluation">
    <svg class="icon icon-sm icon-white">
        <use xlink:href="{% static 'svg/sprites.svg' %}#it-refresh"></use>
    </svg> {% trans "Reopen evaluation" %} {% trans "patronage" %}
</button>
<div class="it-example-modal d-inline">
   <div class="modal" tabindex="-1" role="dialog" id="reopen_evaluation" aria-labelledby="reopen_evaluation-Title">
      <div class="modal-dialog" role="document">
         <div class="modal-content">
            <div class="modal-header">
               <h2 class="modal-title h5 " id="reopen_evaluation-Title">{% trans "Confirm" %}</h2>
               <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Chiudi finestra modale">
                  <svg class="icon"><use href="{% static 'svg/sprites.svg' %}#it-close"></use></svg>
               </button>
            </div>
            <div class="modal-body">
               <p>{% trans "Do you want to reopen evaluation?" %}</p>
            </div>
            <div class="modal-footer">
                <form action="{% url 'pe_management:patronage_operator_event_reopen_evaluation' structure_slug=structure_slug event_id=event.pk %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-warning" type="submit">
                        {% trans 'Yes, proceed' %}
                    </button>
                </form>
            </div>
         </div>
      </div>
   </div>
</div>
{% endif %}
</div>
{% endblock actions %}

uni_pe/template/templates/patronage/events.html
{% extends 'events.html' %}

{% load i18n %}
{% load static %}


{% block top_content %}
<h2>{% trans "Events" %}</h2>
<h3 style="font-weight: lighter">{{ structure_slug|upper }}</h3>
{% endblock top_content %}

{% block custom_filters %}
<div class="form-check form-check-inline">
    <div class="toggles">
      <label for="toggle1">
        {% trans "To be handled" %}
        <input v-model="filter_to_handle" type="checkbox" id="toggle1" @change="to_take($event.target.checked)">
        <span class="lever"></span>
      </label>
    </div>
</div>
<div class="form-check form-check-inline">
    <div class="toggles">
      <label for="toggle12">
        {% trans "To evaluate" %}
        <input v-model="filter_to_evaluate" type="checkbox" id="toggle12" @change="to_evaluate($event.target.checked)">
        <span class="lever"></span>
      </label>
    </div>
</div>
<div class="form-check form-check-inline">
    <div class="toggles">
      <label for="toggle13">
        {% trans "Granted patronage" %}
        <input v-model="filter_evaluation_ok" type="checkbox" id="toggle13" @change="evaluation_ok($event.target.checked)">
        <span class="lever"></span>
      </label>
    </div>
</div>
<div class="form-check form-check-inline">
    <div class="toggles">
      <label for="toggle14">
        {% trans "Denied patronage" %}
        <input v-model="filter_evaluation_ko" type="checkbox" id="toggle14" @change="evaluation_ko($event.target.checked)">
        <span class="lever"></span>
      </label>
    </div>
</div>
{% endblock custom_filters %}