uni_pe/accounts/urls.py
from django.urls import path

from . settings import EDITABLE_FIELDS
from . views import *


app_name = "accounts"

if EDITABLE_FIELDS:
    urlpatterns = [
        path('account/', account, name='account'),
        path('account/edit/', changeData, name='change_data'),
        path('account/edit/confirm-email/', confirmEmail, name='confirm_email'),
    ]
else:
    urlpatterns = []

uni_pe/pe_management/urls.py
from django.urls import path

from . api.views import (generic as api_generic,
                         user as api_user,
                         operator as api_evaluation_operator,
                         patronage as api_patronage_operator,
                         manager as api_manager,
                         involved_personnel as api_involved_personnel,
                         involved_structures as api_involved_structures)

from . views import (generic,
                     involved_personnel,
                     involved_structures,
                     manager,
                     operator,
                     patronage,
                     user)


app_name = 'pe_management'


# app prefix
prefix = 'pe-management'

api_prefix = "api"
user_prefix = 'user'
involved_personnel_prefix = 'involved-personnel'
involved_structures_prefix = 'involved-structures'
operator_prefix = 'operator'
validator_prefix = 'evaluation'
patronage_prefix = 'patronage'
manager_prefix = 'manager'

urlpatterns = [
    path(f'{prefix}/', generic.dashboard, name='dashboard'),
    path(f'{prefix}/events/<int:event_id>/poster/download/',
         generic.download_event_poster, name='download_event_poster'),

    # user
    path(f'{prefix}/{user_prefix}/events/', user.events, name='user_events'),
    path(f'{prefix}/{user_prefix}/events/new/',
         user.new_event_choose_referent, name='user_new_event_choose_referent'),
    path(f'{prefix}/{user_prefix}/events/new/basic-info/',
         user.new_event_basic_info, name='user_new_event_basic_info'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/',
         user.event, name='user_event'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/basic-info/',
         user.event_basic_info, name='user_event_basic_info'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/data/',
         user.event_data, name='user_event_data'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/report/',
         user.event_report, name='user_event_report'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/people/',
         user.event_people, name='user_event_people'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/people/delete/<int:person_id>/',
         user.event_people_delete, name='user_event_people_delete'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/structures/',
         user.event_structures, name='user_event_structures'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/structures/delete/<int:structure_id>/',
         user.event_structures_delete, name='user_event_structures_delete'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/request-evaluation/',
         user.event_request_evaluation, name='user_event_request_evaluation'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/request-evaluation-cancel/',
         user.event_request_evaluation_cancel, name='user_event_request_evaluation_cancel'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/clone/',
         user.event_clone, name='user_event_clone'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/delete/',
         user.event_delete, name='user_event_delete'),

    # evaluation operator
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/',
         operator.dashboard, name='operator_dashboard'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/',
         operator.events, name='operator_events'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/export/',
         operator.export, name='operator_export'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/',
         operator.event, name='operator_event'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/take/',
         operator.take_event, name='operator_take_event'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/basic-info/',
         operator.event_basic_info, name='operator_event_basic_info'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/data/',
         operator.event_data, name='operator_event_data'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/people/',
         operator.event_people, name='operator_event_people'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/people/delete/<int:person_id>/',
         operator.event_people_delete, name='operator_event_people_delete'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/structures/',
         operator.event_structures, name='operator_event_structures'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/structures/delete/<int:structure_id>/',
         operator.event_structures_delete, name='operator_event_structures_delete'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/evaluate/',
         operator.event_evaluation, name='operator_event_evaluation'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/reopen-evaluation/',
         operator.event_reopen_evaluation, name='operator_event_reopen_evaluation'),

    # patronage operator
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/',
         patronage.dashboard, name='patronage_operator_dashboard'),
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/<str:structure_slug>/events/',
         patronage.events, name='patronage_operator_events'),
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/<str:structure_slug>/events/<int:event_id>/',
         patronage.event, name='patronage_operator_event'),
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/<str:structure_slug>/events/<int:event_id>/take/',
         patronage.take_event, name='patronage_operator_take_event'),
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/<str:structure_slug>/events/<int:event_id>/evaluate/',
         patronage.event_evaluation, name='patronage_operator_event_evaluation'),
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/<str:structure_slug>/events/<int:event_id>/reopen-evaluation/',
         patronage.event_reopen_evaluation, name='patronage_operator_event_reopen_evaluation'),

    # involved structures
    path(f'{prefix}/{operator_prefix}/{involved_structures_prefix}/',
         involved_structures.dashboard, name='involved_structures_dashboard'),
    path(f'{prefix}/{operator_prefix}/{involved_structures_prefix}/<str:structure_slug>/events/',
         involved_structures.events, name='involved_structures_events'),
    path(f'{prefix}/{operator_prefix}/{involved_structures_prefix}/<str:structure_slug>/events/<int:event_id>/',
         involved_structures.event, name='involved_structures_event'),

    # manager
    path(f'{prefix}/{manager_prefix}/',
         manager.dashboard, name='manager_dashboard'),
    path(f'{prefix}/{manager_prefix}/export/',
         manager.export, name='manager_export'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/',
         manager.events, name='manager_events'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/new/',
         manager.new_event_choose_referent, name='manager_new_event_choose_referent'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/new/basic-info/',
         manager.new_event_basic_info, name='manager_new_event_basic_info'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/',
         manager.event, name='manager_event'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/basic-info/',
         manager.event_basic_info, name='manager_event_basic_info'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/data/',
         manager.event_data, name='manager_event_data'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/people/',
         manager.event_people, name='manager_event_people'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/people/delete/<int:person_id>/',
         manager.event_people_delete, name='manager_event_people_delete'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/structures/',
         manager.event_structures, name='manager_event_structures'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/structures/delete/<int:structure_id>/',
         manager.event_structures_delete, name='manager_event_structures_delete'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/report/',
         manager.event_report, name='manager_event_report'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/change-status/',
         manager.event_enable_disable, name='manager_event_enable_disable'),

    # involved personnel
    path(f'{prefix}/{involved_personnel_prefix}/events/',
         involved_personnel.events, name='involved_personnel_events'),
    path(f'{prefix}/{involved_personnel_prefix}/events/<int:event_id>/',
         involved_personnel.event, name='involved_personnel_event'),

    # API
    path(f'{prefix}/{api_prefix}/structures/',
         api_generic.OrganizationalStructureList.as_view(), name='api_structures'),
    path(f'{prefix}/{api_prefix}/events/',
         api_generic.PublicEngagementApprovedEventList.as_view(), name='api_generic_approved_events'),
    path(f'{prefix}/{api_prefix}/events/<int:pk>/',
         api_generic.PublicEngagementApprovedEventDetail.as_view(), name='api_generic_approved_event'),
    path(f'{prefix}/{api_prefix}/{user_prefix}/events/',

uni_pe/template/urls.py
from django.urls import path
from pe_management.views import generic

app_name = 'template'

urlpatterns = [
    path('', generic.dashboard, name='dashboard'),
]

uni_pe/uni_pe/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

# from rest_framework.documentation import include_docs_urls
# from rest_framework.schemas import get_schema_view


urlpatterns = [
    path(f'{settings.ADMIN_PATH}/', admin.site.urls),
    # path('docs/', include_docs_urls(title=API_TITLE, description=API_DESCRIPTION)),
    # path('schema/', get_schema_view(title=API_TITLE)),
]

urlpatterns += path('', include('pe_management.urls', namespace='public_engagement')),
urlpatterns += path('', include('template.urls', namespace='template')),
urlpatterns += path('', include('accounts.urls', namespace='accounts')),

if 'saml2_sp' in settings.INSTALLED_APPS:
    from djangosaml2 import views as saml2_views

    import saml2_sp.urls

    urlpatterns += path('', include((saml2_sp.urls, 'sp',))),

    urlpatterns += path('{}/login/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LoginView.as_view(), name='login'),
    urlpatterns += path('{}/acs/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.AssertionConsumerServiceView.as_view(), name='saml2_acs'),
    urlpatterns += path('{}/logout/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LogoutInitView.as_view(), name='logout'),
    urlpatterns += path('{}/ls/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LogoutView.as_view(), name='saml2_ls'),
    urlpatterns += path('{}/ls/post/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LogoutView.as_view(), name='saml2_ls_post'),
    urlpatterns += path('{}/metadata/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.MetadataView.as_view(), name='saml2_metadata'),
else:
    urlpatterns += path('{}/login/'.format(settings.LOCAL_URL_PREFIX),
                        auth_views.LoginView.as_view(
                            template_name='login.html'),
                        name='login'),
    urlpatterns += path('{}/logout/'.format(settings.LOCAL_URL_PREFIX),
                        auth_views.LogoutView.as_view(
                            template_name='logout.html', next_page='/'),
                        name='logout'),

uni_pe/template/templates/base_page.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}


{% block header_wrapper %}
{{ block.super }}
{% include "breadcrumbs.html" %}
{% endblock header_wrapper %}

{% block centered_container %}
    {% block top_content %}
    {% endblock top_content %}

    {% block top_buttons_surround %}
    <div class="mb-4 mt-2">
    {% block top_buttons %}
    {% endblock top_buttons %}
    </div>
    {% endblock top_buttons_surround %}

    {% block over_content %}{% endblock over_content %}

    {% block clean_content %}
    <div class="row">
        <div class="col">
            <div class="card-space card-wrapper">
                <div class="card card-bg no-after">
                    <div class="card-body">
                        {% block page_content %}
                        {% endblock page_content %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock clean_content %}
{% endblock centered_container %}

{% comment %}
{% block bottom_scripts %}
{{ block.super }}
<script>
<!-- Close modal window on submit first click -->
document.querySelectorAll('.modal input[type="submit"]').forEach(function(button) {
    button.addEventListener('click', function(e) {
        // Rimuove la classe "show" dagli elementi con la classe "modal"
        document.querySelectorAll('.modal').forEach(function(modal) {
            modal.classList.remove('show');
        });

        // Cambia l'opacità degli elementi con la classe "modal-backdrop fade"
        document.querySelectorAll('.modal-backdrop.fade').forEach(function(backdrop) {
            backdrop.style.opacity = '0';
        });
    });
});
</script>
{% endblock bottom_scripts %}
{% endcomment %}

uni_pe/template/templates/breadcrumbs.html
{% load i18n %}
{% load static %}


{% if breadcrumbs %}
<nav class="breadcrumb-container" aria-label="Percorso di navigazione" style="border-bottom: 1px solid #ddd;">
    <div class="container">
        <div>
            <ol class="breadcrumb my-2" style="padding-right: 16px; padding-left: 16px">
            {% for k,v in breadcrumbs.items %}
                {% if forloop.last %}
                <li class="breadcrumb-item active" aria-current="page">
                    <a class="breadcrumb-item-active-a" href="{{ k }}">{{ v|truncatechars:40 }}</a>
                </li>
                {% else %}
                <li class="breadcrumb-item">
                    <a href="{{ k }}">{{ v|truncatechars:25 }}</a>
                    <span class="separator">/</span>
                </li>
                {% endif %}
            {% endfor %}
            </ol>
        </div>
    </div>
</nav>
{% endif %}

uni_pe/template/templates/dashboard.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}


{% block top_content %}
<h2>{% trans "UniCal.PE platform" %}</h2>
<p>
    {% trans "In this section you can register and manage the Public Engagement initiatives of the University of Calabria." %}
</p>
{% endblock top_content %}

{% block clean_content %}
<hr class="my-5">
<p class="h5">
    <svg class="icon">
        <use href="{% static 'svg/sprites.svg' %}#it-tool"></use>
    </svg> {% trans "Management tools" %}
</p>
<div class="row mt-5">
    <div class="col-12 col-lg-4">
        <!--start card-->
        <div class="card-wrapper card-space">
            <div class="card card-bg">
                <div class="card-body">
                    <h5 class="card-title">
                        {% trans 'Event referent or his delegate' %}
                    </h5>
                    <p class="card-text">
                        {% trans 'To register or modify an event' %}
                    </p>
                    <a class="read-more" href="{% url 'pe_management:user_events'%}">
                        <span class="text text-primary">{% trans "Manage" %}</span>
                        <svg class="icon">
                            <use href="/static/svg/sprites.svg#it-arrow-right-circle"></use>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
        <!--end card-->
    </div>
    <div class="col-12 col-lg-4">
        <!--start card-->
        <div class="card-wrapper card-space">
            <div class="card card-bg">
                <div class="card-body">
                    <h5 class="card-title">
                        {% trans 'Structure operator' %}
                    </h5>
                    <p class="card-text">
                        {% trans 'To manager structure events' %}
                    </p>
                    <a class="read-more" href="{% url 'pe_management:operator_dashboard'%}">
                        <span class="text text-primary">{% trans "Evaluation" %}</span>
                        <svg class="icon">
                            <use href="/static/svg/sprites.svg#it-arrow-right-circle"></use>
                        </svg>
                    </a>
                    <a class="read-more" style="left: 50%" href="{% url 'pe_management:patronage_operator_dashboard'%}">
                        <span class="text text-primary">{% trans "Patronage" %}</span>
                        <svg class="icon">
                            <use href="/static/svg/sprites.svg#it-arrow-right-circle"></use>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
        <!--end card-->
    </div>
    <div class="col-12 col-lg-4">
        <!--start card-->
        <div class="card-wrapper card-space">
            <div class="card card-bg">
                <div class="card-body">
                    <h5 class="card-title">
                        {% trans 'Manager' %}
                    </h5>
                    <p class="card-text">
                        {% trans 'To manage all events' %}
                    </p>
                    <a class="read-more" href="{% url 'pe_management:manager_dashboard'%}">
                        <span class="text text-primary">{% trans "Manage" %}</span>
                        <svg class="icon">
                            <use href="/static/svg/sprites.svg#it-arrow-right-circle"></use>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
        <!--end card-->
    </div>
</div>
<hr class="my-5">
<p class="h5">
    <svg class="icon">
        <use href="{% static 'svg/sprites.svg' %}#it-password-visible"></use>
    </svg> {% trans "Read only access" %}
</p>
<div class="row mt-5">
    <div class="col-12 col-lg-4">
        <!--start card-->
        <div class="card-wrapper card-space">
            <div class="card card-bg">
                <div class="card-body">
                    <h5 class="card-title">
                        {% trans 'Other involved personnel' %}
                    </h5>
                    <p class="card-text">
                        {% trans 'Access the data of the initiatives in which you have been included as "other involved personnel"' %}
                    </p>
                    <a class="read-more" href="{% url 'pe_management:involved_personnel_events'%}">
                        <span class="text text-primary">{% trans "Enter" %}</span>
                        <svg class="icon">
                            <use href="/static/svg/sprites.svg#it-arrow-right-circle"></use>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
        <!--end card-->
    </div>
    <div class="col-12 col-lg-4">
        <!--start card-->
        <div class="card-wrapper card-space">
            <div class="card card-bg">
                <div class="card-body">
                    <h5 class="card-title">
                        {% trans 'Other involved structures' %}
                    </h5>
                    <p class="card-text">
                        {% trans 'Access the data of the initiatives in which your structure has been involved' %}
                    </p>
                    <a class="read-more" href="{% url 'pe_management:involved_structures_dashboard'%}">
                        <span class="text text-primary">{% trans "Enter" %}</span>
                        <svg class="icon">
                            <use href="/static/svg/sprites.svg#it-arrow-right-circle"></use>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
        <!--end card-->
    </div>
</div>
{% endblock clean_content %}

uni_pe/template/templates/event_basic_info.html
{% extends 'base.html' %}}

{% load i18n %}
{% load static %}
{% load generic_tags %}


{% block top_content %}
<h2>{% if event %}{{ event.title }}{% else %}Nuova iniziativa{% endif %}</h2>
<h3 style="font-weight: lighter">Informazioni generali</h3>

{% if request.session.referent %}
{% user_from_pk request.session.referent as referent %}
{% if referent %}
<div class="alert alert-info my-5" role="alert">
    <b>Referente scelto:</b> {{ referent }}
</div>
{% endif %}
{% endif %}
{% endblock top_content %}

{% block page_content %}
{% include "form_template.html" with form=form %}
{% endblock page_content %}

uni_pe/template/templates/event_data.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}


{% block top_content %}
<h2>{{ event.title }}</h2>
<h3 style="font-weight: lighter">Dati dell'iniziativa</h3>
{% endblock top_content %}

{% block page_content %}
{% include "form_template.html" with form=form %}
{% endblock page_content %}

uni_pe/template/templates/event_evaluation.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}


{% block top_content %}
<h2>{{ event.title }}</h2>
<h3 style="font-weight: lighter">{% trans "Evaluation" %}</h3>
{% endblock top_content %}

{% block page_content %}
{% include "form_template.html" with form=form %}
{% endblock page_content %}

uni_pe/template/templates/event_new.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}
{% load pe_management_tags %}


{% block top_content %}
<h2>Nuova iniziativa</h2>
<h3 style="font-weight: lighter">Scelta referente</h3>
{% endblock top_content %}

{% block page_content %}
{% pem_settings_value "API_ADDRESSBOOK" as addressbook_api_url %}
<div id="addressbook">
    <div class="row">
        <div class="col">
            <form class="d-inline" method="post" noevaluate>
                {% if compiled_by_user %}
                <fieldset class="mb-3">
                    <div class="form-check">
                        <input name="user_is_referent" type="radio" id="radio1" value="true" checked v-model="user_is_referent">
                        <label for="radio1">{% trans "It's me" %}</label>
                    </div>
                    <div class="form-check">
                        <input name="user_is_referent" type="radio" id="radio2" value="false" v-model="user_is_referent">
                        <label for="radio2">
                            {% trans "I'm referent delegate" %}
                        </label>
                    </div>
                </fieldset>
                {% endif %}

                <div class="card-wrapper pb-0 my-3" v-if="referent_name && user_is_referent == 'false'">
                    <div class="card no-after" style="border:1px solid #b71918">
                        <div class="card-body p-3">
                            <div class="row">
                                <div class="col-12 align-left">
                                    <span>
                                        <b>[[ referent_name ]]</b>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <input type="hidden" name="referent_id" :value="referent_id" />
                {% csrf_token %}

                {% if compiled_by_user %}
                <button type="submit" class="btn btn-success" v-if="user_is_referent == 'true' || referent_id != ''">
                {% else %}
                <button type="submit" class="btn btn-success" v-if="referent_id != ''">
                {% endif %}
                    {% trans "Next step" %}
                </button>
            </form>
            {% if compiled_by_user %}
            <button class="d-inline btn btn-danger ms-2" v-if="user_is_referent == 'false' && referent_id != ''" @click="delete_selected_referent()">
            {% else %}
            <button class="d-inline btn btn-danger ms-lg-2" v-if="referent_id != ''" @click="delete_selected_referent()">
            {% endif %}
                Cancella
            </button>
        </div>
    </div>

    {% if compiled_by_user %}
    <div v-if="user_is_referent == 'false' && referent_id == ''">
    {% else %}
    <div v-if="referent_id == ''">
    {% endif %}
        <div class="row form-group">
            <div class="col-md">
                <div class="form-group mb-0">
                    <input type="text"
                           class="form-control"
                           id="search"
                           name="search"
                           placeholder="{% trans 'Surname' %}"
                           v-model="search_terms"
                           v-on:keyup.enter="search()">
                    <span class="autocomplete-icon" style="background: none">
                        <svg class="icon icon-sm">
                            <use xlink:href="{% static 'svg/sprites.svg' %}#it-search"></use>
                        </svg>
                    </span>
                </div>
            </div>
        </div>
        <div v-if="is_loading">{% include "loader.html" %}</div>
        <div v-else>
            {% include "pagination.html" %}
            <div class="row w-100">
                <div class="col-12 col-md-6 mb-3" v-for="item in data.results">
                    <div class="card-wrapper pb-0">
                        <div class="card no-after" style="border:1px solid #b71918">
                            <div class="card-body p-3">
                                <div class="row">
                                    <div class="col-12 align-left">
                                        <span>
                                            <b>[[ item.Name ]]</b>
                                            <br>
                                            <div v-for="role in item.Roles">
                                                <span>
                                                    [[ role.RoleDescription ]]
                                                    <br>
                                                    [[ role.Structure ]]
                                                </span>
                                                <br>
                                            </div>
                                            <div v-for="email in item.Email">
                                                <span>
                                                    <svg class="icon icon-sm icon-muted me-2">
                                                        <use xlink:href="{% static 'svg/sprites.svg' %}#it-mail"></use>
                                                    </svg>
                                                    <a :href="'mailto:'+email">[[ email ]]</a>
                                                </span>
                                                <br>
                                            </div>
                                        </span>
                                        <span class="mt-3 btn btn-success" @click="set_external_referent(item.ID, item.Name)">inserisci</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% include "pagination.html" %}
        </div>
    </div>
</div>
<script>
const app = Vue.createApp({
    delimiters: ['[[', ']]'],
    data () {
        return {
            data: [],
            is_loading: false,
            user_is_referent: {% if compiled_by_user %}'true'{% else %}'false'{% endif %},
            referent_id: '',
            referent_name: '',
            search_terms: '',
            controller: null,
            url: '{{ addressbook_api_url }}'
        }
    },
    mounted () {
    },
    methods: {
        set_external_referent(id, name, role, department) {
            this.referent_id = id
            this.referent_name = name
        },
        delete_selected_referent() {
            this.referent_id = ''
            this.referent_name = ''
        },
        search() {
            if(this.controller) this.controller.abort()
            if(this.search_terms) this.getData(page=1);
            else this.data = []
        },
        getData(page=1, search=this.search_terms) {
            this.controller = new AbortController()
            let signal = this.controller.signal
            let url = this.url+'?page='+page
            if(search) url += '&search='+search
            this.is_loading = true
            axios
                .get(url, {signal})
                .then(
                    response => {
                        this.is_loading = false
                        this.data = response.data
                    }
                )
                .catch((error) => {});
        },
    },
}).mount('#addressbook')
</script>
{% endblock page_content %}

uni_pe/template/templates/export.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}
{% load generic_tags %}


{% block top_content %}
<h2>{% trans "Export" %} DB</h2>
{% endblock top_content %}

{% block page_content %}
<form method="post">
    <div class="row">
        <div class="col-12 mt-4">
            <div class="select-wrapper">
                <label for="year">{% trans "Year" %}</label>
                <select id="year" name="year">
                    {% year_list as year_list %}
                    {% for year in year_list %}
                    <option value="{{ year }}">{{ year }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-12">
            <input class="btn btn-success"
                   type="submit"
                   id="submitForm"
                   value="{% trans 'Download' %}">
            </div>
        </div>
    </div>
    {% csrf_token %}
</form>
{% endblock page_content %}